version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8081:8081
      - 9229:9229
    working_dir: /app
    command: npm start
    depends_on:
      - db
  db:
    image: mongo:4.0.9
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
